### ISSUE TITLE
Expanding adds quotes around unquoted font-families

### ISSUE THREAD

**Issue by bartveneman** [kapetan/css-shorthand-expand#8]
See the following fixture for the font shorthand:

```json
"oblique 500 small-caps semi-expanded 20% / 2em monospace, \"Times New Roman\", Helvetica": {
  "font-size": "20%",
  "line-height": "2em",
  "font-style": "oblique",
  "font-weight": "500",
  "font-variant": "small-caps",
  "font-stretch": "semi-expanded",
  "font-family": "monospace, \"Times New Roman\", \"Helvetica\""
}
```

It adds quotes around `Helvetica`, while the original input doesn't have these quotes. I think the original values should be left as-is. 

My particular issue is a tool that analyses some CSS and it reports the following lines as different font-stacks, while they are actually the same:

```css
.selector {
  font: 11px Consolas, "Liberation Mono", Menlo, Courier, monospace;
  font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
}

/**
 * Outputs these two font-stacks:
 * 1. "Consolas", "Liberation Mono", "Menlo", "Courier", monospace
 * 2. Consolas, "Liberation Mono", Menlo, Courier, monospace
 */
```
